version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo Done installing nodejs version 18 in environment

  build:
    commands:
      - echo Installing node modules...
      - npm ci
      - npm run build

  post_build:
    on-failure: CONTINUE
    commands:
      - echo Running package analysis...
      - npm audit
    finally:
      - echo Tests and analysis completed...
